name: chewbbaca

on:
  push:
    branches: [ csis_testing ]
  pull_request:
    branches: [ csis_testing ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - uses: actions/checkout@v2
      with:
        repository: B-UMMI/chewBBACA
        path: chewbbaca
    - name: List dir
      run: |
        cd $GITHUB_WORKSPACE/chewbbaca
        ls -lah
    - name: Install chewbbaca
      run: |
        python setup.py install
    - name: Basic testing
      run: |
        which chewBBACA.py
        chewBBACA.py -h
        chewBBACA.py --help
        chewBBACA.py -v
        chewBBACA.py --version
        chewBBACA.py CreateSchema -h
        chewBBACA.py CreateSchema --help
        chewBBACA.py AlelleCall -h
        chewBBACA.py AlelleCall --help
        chewBBACA.py TestGenomeQuality -h
        chewBBACA.py TestGenomeQuality --help
        chewBBACA.py ExtractCgMLST -h
        chewBBACA.py ExtractCgMLST --help
        chewBBACA.py SchemaEvaluator -h
        chewBBACA.py SchemaEvaluator --help
        chewBBACA.py DownloadSchema -h
        chewBBACA.py DownloadSchema --help
        chewBBACA.py LoadSchema -h
        chewBBACA.py LoadSchema --help
        chewBBACA.py SyncSchema -h
        chewBBACA.py SyncSchema --help
        chewBBACA.py NSStats -h
        chewBBACA.py NSStats --help
    - name: Run Pytest
      run: |
        pushd CHEWBBACA/tests
        pytest
        popd
