name: chewbbaca

on:
  push:
    branches: [ csis_testing ]
  pull_request:
    branches: [ csis_testing ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - uses: actions/checkout@v2
      with:
        repository: B-UMMI/chewBBACA
        path: chewbbaca
    - name: List dir
      run: |
        cd $GITHUB_WORKSPACE/chewbbaca
        ls -lah
    - name: Install chewbbaca
      run: |
        python setup.py install
    - name: Test help
      run: |
        which chewBBACA.py
        chewBBACA.py -h
    - name: Run Pytest
      run: |
        pytest
